# Konfigurationsdatei für JAKA Zu 7 RoboDK-Steuerung
# Diese Parameter werden in program_runner.py verwendet

robot_name: JAKA Zu7
pick_target: PickTarget
place_target: PlaceTarget
use_random_input: true
sensor_intervals: [2, 3, 1.5, 4, 2.5]
num_cycles: 10
use_virtual_io: true
debug_mode: true
log_to_file: true
# ... bestehende Konfiguration ...

palettierung:
  muster: "spirale"
  ablagepunkte:
    - [100, 200, 300]
    - [120, 200, 300]
  zufall: true
  wiederholung: 3

qs:
  aktiv: true
  kameramodell: "opencv_mock"
  auswertelogik: "kontur > 80%"
  fehlerhandling: "ablage_defekt"
